<?php

namespace Modules\Student\Http\Controllers;

use App\Models\Course;
use App\Models\EnrollCourseRequest;
use App\Models\StudentCourse;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class CourseController extends BaseController
{


    protected $config = array(
        'addBtn' => false,
        'editBtn' => false,
        'deleteBtn' => false,
        'deleteGroupAction' => false,
        'deleteAction' => false,
        'importBtn' => false,
        'trash' => false,
        'showAction' => false,
        'status_btn' => true
    );


    protected $appended_actions = array(
        'enroll'
    );

    public function getQuery()
    {
        /*
         * ->whereHas('specializations',function ($query){
            $query->where('id',auth()->user()->specialization_id);
        })
         */
        $q = parent::getQuery(); // TODO: Change the autogenerated stub
        $q->where(function ($inner) {
            $inner->whereHas('studentRequest', function ($q) {
                $q->where('status', '!=', 'accepted');
            })->orWhereDoesntHave('studentRequest');
        });
        return $q;
    }

    public function enroll(Request $request)
    {
        $model = EnrollCourseRequest::create(array(
            'student_id' => auth()->id(),
            'course_id' => $request->get('id'),
            'course_data' => Course::find($request->get('id')),
            'student_data' => auth()->user(),
            'status' => 'pending'
        ));
        return response()->json(array('status' => true, 'model' => $model));
    }
}
