<?php

namespace Modules\Student\Http\Controllers;

use App\Models\Course;
use App\Models\EnrollCourseRequest;
use App\Models\StudentCourse;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class CourseController extends BaseController
{


    protected $config = array(
        'addBtn' => false,
        'editBtn' => false,
        'deleteBtn' => false,
        'deleteGroupAction' => false,
        'deleteAction' => false,
        'importBtn' => false,
        'trash' => false,
        'showAction' => false,
        'status_btn' => true,
        'slot' => 'dash.list.components.student_course'
    );


    protected $appended_actions = array(
        'enroll'
    );


    public function getQuery()
    {
        $q = parent::getQuery(); // TODO: Change the autogenerated stub
        $requestValue = get(explode(',', get(request()->get('search'), 'value')), 1, null);
        $q->where(function ($inner) use ($requestValue) {
            if ($requestValue) {
                $inner->whereHas('studentRequest', function ($q) use ($requestValue) {
                    $q->where('status', $requestValue);
                });
            }else {
                $inner->whereDoesntHave('studentRequest');
            }

        })->where('semester_id', get(current_semester(), 'id'));
        return $q;
    }

    public function enroll(Request $request)
    {
        $course = Course::find($request->get('id'));
        $user = auth()->user();
        $hours_count = current_semester_hours_count($user);
        if (!current_semester())
            return response()->json(array('status' => false, 'message' => 'الفصل الحالي لم يبدأ بعد'));

        if (($hours_count + $course->hour_number) > current_semester()->number_of_hour)
            return response()->json(array('status' => false, 'message' => 'لقد تجاوزت عدد الساعات المسموح بها للفصل الحالي'));

        if (auth()->user()->balance < ($course->hour_number * get($user, 'specialization.hour_price', 1)))
            return response()->json(array('status' => false, 'message' => 'عذرا .. قم بتسوية وضعك المالي'));


        $model = EnrollCourseRequest::create(array(
            'student_id' => auth()->id(),
            'course_id' => $request->get('id'),
            'course_data' => Course::find($request->get('id')),
            'student_data' => auth()->user(),
            'status' => 'pending'
        ));
        return response()->json(array('status' => true, 'model' => $model));
    }
}
