<?php

namespace Modules\Student\Http\Controllers;

use App\Models\Course;
use App\Models\StudentCourse;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class StudentCourseController extends BaseController
{
    protected $config = NO_ACTIONS_LIST;

    public function getQuery()
    {

        $q = parent::getQuery(); // TODO: Change the autogenerated stub
        $requestValue = explode(',', get(request()->get('search'),'value'));
          $q->whereHas('course',function ($inner) use($requestValue) {
             $inner->where('semester_id',get($requestValue,'1'));
         });
          return $q;
    }
}
