<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class CourseController extends BaseController
{

//    public function saving($model, $request)
//    {
//        $model->specializations()->sync($request->get('specializations'));
//        return parent::saving($model, $request); // TODO: Change the autogenerated stub
//    }

}
