<?php

namespace Modules\Admin\Http\Controllers;

use App\Models\Semester;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class SemesterController extends BaseController
{
    public function store(Request $request)
    {
        $exists = Semester::query()->where(collect(request()->all())->only('study_plan_id', 'year', 'ordered')->toArray())->exists();
        if ($exists)
            return redirect()->back()->withErrors('الفصل المراد اضافته مضاف مسبقاً');

        if ($request->number_of_hour > 18)
            return redirect()->back()->withErrors('يجب ألا يتجاوز قيمة عدد الساعات عن 18 ساعة');

        return parent::store($request); // TODO: Change the autogenerated stub
    }

}
