<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class SemesterController extends BaseController
{
//public function getAttributes($request)
//{
//    dd($request->all());
//    return parent::getAttributes($request); // TODO: Change the autogenerated stub
//}

}
