<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Base\Http\Controllers\BaseController;

class StudentController extends BaseController
{
public function getAttributes($request)
{
    $data = parent::getAttributes($request); // TODO: Change the autogenerated stub
    $data['student_id'] = '12023'.$request->get('student_id');
    return $data;
}
}
